# Generated by Django 4.1.1 on 2022-12-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcceptedPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash Payment"),
                            ("POS", "POS"),
                            ("TF", "Bank Transfer"),
                            ("O", "Others"),
                        ],
                        default="CASH",
                        max_length=4,
                    ),
                ),
                ("description", models.TextField()),
                ("charges", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name_plural": "payment methods",
                "db_table": "sql_payment_method",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "sql_category",
            },
        ),
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("local_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[("", ""), ("New", "New"), ("Old", "Old")],
                        default="",
                        max_length=4,
                    ),
                ),
                ("overview", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="markets.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "commodities",
                "db_table": "sql_commodity",
            },
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "sql_market_extension_officer",
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                ("market_code", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(editable=False, max_length=500, null=True)),
                ("brief_detail", models.TextField()),
                ("num_vendor", models.SmallIntegerField()),
                ("market_days_interval", models.SmallIntegerField(default=5)),
                ("location_description", models.TextField(verbose_name="Market site")),
                (
                    "reference_mkt_date",
                    models.DateField(verbose_name="confirmed market date"),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "accepted_payment_types",
                    models.ManyToManyField(
                        to="markets.acceptedpaymentmethod",
                        verbose_name="list of payment methods",
                    ),
                ),
            ],
            options={
                "db_table": "sql_market",
                "ordering": ["market_code"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="markets.market"
                    ),
                ),
            ],
            options={
                "db_table": "sql_market_review",
            },
        ),
        migrations.CreateModel(
            name="MarketCommodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commodity_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price per bag",
                        max_digits=8,
                        null=True,
                        verbose_name="price per bag",
                    ),
                ),
                ("market_date", models.DateField(blank=True, null=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="markets.commodity",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="markets.market"
                    ),
                ),
            ],
            options={
                "verbose_name": "market commodities",
                "verbose_name_plural": "market commodities",
                "db_table": "sql_market_commodity",
            },
        ),
        migrations.AddField(
            model_name="market",
            name="commodities",
            field=models.ManyToManyField(
                through="markets.MarketCommodity",
                to="markets.commodity",
                verbose_name="list of commodities",
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="markets.contactperson",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketcommodity",
            constraint=models.UniqueConstraint(
                fields=("commodity", "market", "market_date"), name="unique_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="commodity",
            constraint=models.UniqueConstraint(
                fields=("name", "grade"), name="unique_commodity"
            ),
        ),
    ]
