# Generated by Django 4.1.1 on 2022-12-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MarketInstance",
            new_name="MarketCommodity",
        ),
        migrations.AlterField(
            model_name="commodity",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[("NONE", "None"), ("New", "New"), ("Old", "Old")],
                default="NONE",
                max_length=4,
            ),
        ),
    ]
