# Generated by Django 4.1.1 on 2022-12-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
