# Generated by Django 4.1.1 on 2022-12-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_market_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="status",
            field=models.CharField(
                choices=[
                    ("AP", "Awaiting Approval"),
                    ("A", "Approved"),
                    ("D", "Declined"),
                ],
                default="AP",
                max_length=2,
            ),
        ),
    ]
