# Generated by Django 4.1.1 on 2022-12-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0004_remove_market_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="address",
            field=models.CharField(max_length=100, null=True, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="market",
            name="country",
            field=models.CharField(max_length=100, null=True, verbose_name="country"),
        ),
        migrations.AddField(
            model_name="market",
            name="latitude",
            field=models.CharField(max_length=50, null=True, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="market",
            name="local_govt",
            field=models.CharField(
                max_length=100, null=True, verbose_name="local government area"
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="longitude",
            field=models.CharField(max_length=50, null=True, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="market",
            name="post_code",
            field=models.CharField(max_length=8, null=True, verbose_name="post code"),
        ),
        migrations.AddField(
            model_name="market",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default="2022-12-14 16:36:34"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="market",
            name="town",
            field=models.CharField(max_length=100, null=True, verbose_name="town"),
        ),
        migrations.AddField(
            model_name="market",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
