# Generated by Django 4.1.1 on 2022-10-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcceptedPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash Payment"),
                            ("POS", "POS"),
                            ("TF", "Bank Transfer"),
                            ("O", "Others"),
                        ],
                        default="CASH",
                        max_length=4,
                        verbose_name="Accepted Payments",
                    ),
                ),
                ("description", models.TextField()),
                ("charges", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name_plural": "Payment Methods",
                "db_table": "sql_payment_method",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "sql_category",
            },
        ),
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "grade",
                    models.CharField(
                        choices=[("", "---"), ("New", "New"), ("Old", "Old")],
                        default="",
                        max_length=3,
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commodity Description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mktdirectory.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Commodities",
                "db_table": "sql_commodity",
            },
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "sql_contact_person",
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                ("market_code", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("brief_detail", models.TextField()),
                ("num_vendor", models.SmallIntegerField()),
                ("market_days_interval", models.SmallIntegerField(default=5)),
                ("location_description", models.TextField(verbose_name="Market site")),
                (
                    "reference_mkt_date",
                    models.DateField(verbose_name="confirmed market date"),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "accepted_payment_types",
                    models.ManyToManyField(to="mktdirectory.acceptedpaymentmethod"),
                ),
            ],
            options={
                "db_table": "sql_market",
                "ordering": ["market_code"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mktdirectory.market",
                    ),
                ),
            ],
            options={
                "db_table": "sql_market_review",
            },
        ),
        migrations.CreateModel(
            name="MarketDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commodity_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per bag",
                        max_digits=8,
                        verbose_name="Price per bag",
                    ),
                ),
                ("market_date", models.DateField(verbose_name="Market date")),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="mktdirectory.commodity",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mktdirectory.market",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Date",
                "db_table": "sql_market_date",
            },
        ),
        migrations.AddField(
            model_name="market",
            name="commodities",
            field=models.ManyToManyField(
                through="mktdirectory.MarketDay", to="mktdirectory.commodity"
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mktdirectory.contactperson",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketday",
            constraint=models.UniqueConstraint(
                fields=("commodity", "market_date"), name="unique_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="commodity",
            constraint=models.UniqueConstraint(
                fields=("name", "grade"), name="unique_commodity"
            ),
        ),
    ]
