# Generated by Django 4.1.1 on 2022-09-26 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcceptedPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Accepted Payments"),
                ),
                ("description", models.TextField()),
                ("charges", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "Payment Methods",
                "db_table": "sql_payment_method",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "sql_category",
            },
        ),
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "overview",
                    models.TextField(verbose_name="Brief description of the commodity"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mktdirectory.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Commodities",
                "db_table": "sql_commodity",
            },
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "sql_contact_person",
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "market_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("brief_details", models.TextField()),
                ("num_vendors", models.SmallIntegerField()),
                ("market_schedule", models.CharField(max_length=50)),
                ("location_description", models.TextField(verbose_name="Market site")),
                ("slug", models.SlugField(max_length=200)),
                (
                    "reference_mkt_date",
                    models.DateField(verbose_name="Most recent market date"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "accepted_payments",
                    models.ManyToManyField(to="mktdirectory.acceptedpaymentmethod"),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mktdirectory.contactperson",
                    ),
                ),
            ],
            options={
                "db_table": "sql_market",
            },
        ),
        migrations.CreateModel(
            name="MarketDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[("O", "New"), ("N", "Old")], default="N", max_length=1
                    ),
                ),
                (
                    "commodity_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per bag",
                        max_digits=8,
                        verbose_name="Price per bag at market date",
                    ),
                ),
                ("market_date", models.DateField(verbose_name="Market day")),
                (
                    "commodity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mktdirectory.commodity",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mktdirectory.market",
                    ),
                ),
            ],
            options={
                "db_table": "sql_market_date",
            },
        ),
    ]
