# Generated by Django 4.1.1 on 2022-09-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
