# Generated by Django 4.1.1 on 2022-09-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptedpaymentmethod",
            name="name",
            field=models.CharField(
                choices=[
                    ("C", "Cash Payment"),
                    ("P", "POS"),
                    ("B", "Bank Transfer"),
                    ("O", "Others"),
                ],
                default="C",
                max_length=1,
                verbose_name="Accepted Payments",
            ),
        ),
    ]
