# Generated by Django 4.1.1 on 2022-10-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="local_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("New", "New"), ("Old", "Old")],
                default="",
                max_length=3,
            ),
        ),
    ]
