# Generated by Django 4.1.1 on 2022-10-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="grade",
            field=models.CharField(
                choices=[("New", "New"), ("Old", "Old"), ("", "")],
                default="New",
                max_length=3,
            ),
        ),
    ]
