# Generated by Django 4.1.1 on 2022-12-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="marketinstance",
            table="sql_market_instance",
        ),
    ]
