# Generated by Django 4.1.1 on 2022-09-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0002_alter_acceptedpaymentmethod_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="market",
            old_name="accepted_payments",
            new_name="accepted_payment_types",
        ),
        migrations.AlterField(
            model_name="acceptedpaymentmethod",
            name="charges",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="acceptedpaymentmethod",
            name="name",
            field=models.CharField(
                choices=[
                    ("CAS", "Cash Payment"),
                    ("POS", "POS"),
                    ("TF", "Bank Transfer"),
                    ("O", "Others"),
                ],
                default="CAS",
                max_length=3,
                verbose_name="Accepted Payments",
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mktdirectory.contactperson",
            ),
        ),
    ]
