# Generated by Django 4.1.1 on 2022-09-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0003_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MarketAcceptedPayments",
            new_name="MarketAcceptedPayment",
        ),
        migrations.AlterModelOptions(
            name="marketacceptedpayment",
            options={"verbose_name_plural": "Market Accepted Payments"},
        ),
    ]
