# Generated by Django 4.1.1 on 2022-10-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0003_remove_marketday_unique_item"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="marketday",
            constraint=models.UniqueConstraint(
                fields=("commodity", "market", "market_date"), name="unique_item"
            ),
        ),
    ]
