# Generated by Django 4.1.1 on 2022-09-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mktdirectory",
            "0003_rename_accepted_payments_market_accepted_payment_types_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
