# Generated by Django 4.1.1 on 2022-09-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0004_add_unique_to_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="title",
            new_name="name",
        ),
    ]
