# Generated by Django 4.1.1 on 2022-10-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0004_alter_commodity_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="overview",
            field=models.TextField(
                blank=True, null=True, verbose_name="Commodity Description"
            ),
        ),
    ]
