# Generated by Django 4.1.1 on 2022-09-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mktdirectory",
            "0004_rename_marketacceptedpayments_marketacceptedpayment_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
    ]
