# Generated by Django 4.1.1 on 2022-09-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0005_rename_title_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="modified_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="marketday",
            name="commodity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mktdirectory.commodity",
            ),
            preserve_default=False,
        ),
    ]
