# Generated by Django 4.1.1 on 2022-09-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0005_rename_title_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketday",
            name="commodity",
            field=models.ForeignKey(
                default="-",
                on_delete=django.db.models.deletion.CASCADE,
                to="mktdirectory.commodity",
            ),
            preserve_default=False,
        ),
    ]
