# Generated by Django 4.1.1 on 2022-09-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0005_alter_category_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="sql_category",
        ),
        migrations.AlterModelTable(
            name="commodity",
            table="sql_commodity",
        ),
        migrations.AlterModelTable(
            name="market",
            table="sql_market",
        ),
        migrations.AlterModelTable(
            name="marketacceptedpayment",
            table="sql_accepted_payment",
        ),
        migrations.AlterModelTable(
            name="paymentmethod",
            table="sql_payment_method",
        ),
    ]
