# Generated by Django 4.1.1 on 2022-10-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0005_alter_commodity_overview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mktdirectory.contactperson",
            ),
        ),
    ]
