# Generated by Django 4.1.1 on 2022-09-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0006_alter_commodity_created_at_and_more"),
        ("mktdirectory", "0006_alter_marketday_commodity"),
    ]

    operations = []
