# Generated by Django 4.1.1 on 2022-09-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0006_alter_category_table_alter_commodity_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[("O", "Old"), ("N", "New")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "commodity_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per bag",
                        max_digits=6,
                        verbose_name="Price per bag at market date",
                    ),
                ),
                ("market_date", models.DateField(verbose_name="Market day")),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mktdirectory.commodity",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mktdirectory.market",
                    ),
                ),
            ],
            options={
                "db_table": "sql_market_instance",
            },
        ),
    ]
