# Generated by Django 4.1.1 on 2022-10-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0006_alter_market_contact_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="market_code",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
