# Generated by Django 4.1.1 on 2022-09-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0007_merge_20220927_1850"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="market",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="market",
            name="market_schedule",
        ),
        migrations.AddField(
            model_name="market",
            name="market_days_interval",
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mktdirectory.category"
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="market",
            name="slug",
            field=models.SlugField(),
        ),
    ]
