# Generated by Django 4.1.1 on 2022-09-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0007_marketinstance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="market",
            old_name="referene_mkt_date",
            new_name="reference_mkt_date",
        ),
    ]
