# Generated by Django 4.1.1 on 2022-10-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0007_alter_market_market_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mktdirectory.contactperson",
            ),
        ),
        migrations.AlterField(
            model_name="marketday",
            name="commodity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="mktdirectory.commodity",
            ),
        ),
    ]
