# Generated by Django 4.1.1 on 2022-10-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0008_alter_market_contact_person_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="market",
            old_name="brief_details",
            new_name="brief_detail",
        ),
        migrations.RenameField(
            model_name="market",
            old_name="num_vendors",
            new_name="num_vendor",
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mktdirectory.market",
                    ),
                ),
            ],
        ),
    ]
