# Generated by Django 4.1.1 on 2022-09-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0008_remove_market_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="market_code",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
