# Generated by Django 4.1.1 on 2022-09-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0009_alter_market_market_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marketday",
            options={"ordering": ["-market_date"], "verbose_name": "Market Date"},
        ),
    ]
