# Generated by Django 4.1.1 on 2022-09-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0010_alter_marketday_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="market",
            options={"ordering": ["market_code"]},
        ),
        migrations.AlterModelOptions(
            name="marketday",
            options={"verbose_name": "Market Date"},
        ),
        migrations.RenameField(
            model_name="acceptedpaymentmethod",
            old_name="name",
            new_name="type",
        ),
        migrations.AlterField(
            model_name="commodity",
            name="overview",
            field=models.TextField(verbose_name="Commodity Description"),
        ),
    ]
