# Generated by Django 4.1.1 on 2022-09-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0011_alter_market_options_alter_marketday_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptedpaymentmethod",
            name="type",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash Payment"),
                    ("POS", "POS"),
                    ("TF", "Bank Transfer"),
                    ("O", "Others"),
                ],
                default="CASH",
                max_length=4,
                verbose_name="Accepted Payments",
            ),
        ),
    ]
