# Generated by Django 4.1.1 on 2022-09-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0012_alter_acceptedpaymentmethod_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptedpaymentmethod",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
