# Generated by Django 4.1.1 on 2022-09-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0013_acceptedpaymentmethod_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acceptedpaymentmethod",
            name="first_name",
        ),
    ]
