# Generated by Django 4.1.1 on 2022-09-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mktdirectory", "0014_remove_acceptedpaymentmethod_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketday",
            name="commodity_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price per bag",
                max_digits=8,
                verbose_name="Price per bag",
            ),
        ),
    ]
